name: AI PR Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize]

  # Grant permission to comment on PR

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r review_agents/requirements.txt

      - name: Run AI PR Reviewer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
        run: |
          python add